# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Sarsi spellchecker"
srs = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Sarsi, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
srs = "TRANSLATE: A spellchecker for Sarsi, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.srs"

[windows]
system_product_code = "{D2243E81-1D6E-4307-A686-BA92A877F963}_is1"
legacy_product_codes = [
    { value = "72764F3E-D461-42D8-BAFE-BBF3CF93D7BD", kind = "nsis" },
    { value = "3598DFFC-3AD4-4D8F-82FD-8D2CD69B5AE0", kind = "nsis" }
]

[package.speller]
name = "Sarsi"
version = "0.1.1"

[package.grammar]
name = "Sarsi"
version = "0.1.0"

[package.tts-text-proc]
name = "Sarsi"
version = "0.1.0"

[package.hyphenator]
name = "__UNDEFINED__"
version = "0.1.0"
